const state={snapshot:null,records:[],visibleState:null,source:null,normalized:null,recommendation:null};const $=s=>document.querySelector(s);
const money=n=>n==null?'—':'$'+Number(n).toLocaleString('en-US',{maximumFractionDigits:0});
const num=v=>{if(typeof v==='number')return Number.isFinite(v)?v:null;if(typeof v==='string'){const n=Number(v.replace(/[$, ]/g,''));return Number.isFinite(n)?n:null}return null};
function walk(x,fn,d=0,seen=new Set()){if(x==null||d>8||typeof x!=='object'||seen.has(x))return;seen.add(x);fn(x);if(Array.isArray(x))x.slice(0,500).forEach(v=>walk(v,fn,d+1,seen));else Object.values(x).slice(0,500).forEach(v=>walk(v,fn,d+1,seen))}
function flattenObjects(records){const out=[];for(const r of records||[]){try{const o=JSON.parse(r.body);walk(o,n=>{if(!Array.isArray(n))out.push({...n,__category:r.category,__url:r.url})})}catch{}}return out}
function extract(){let cash=null,aircraft=null,routes=null,hubs=null;const counts={fleet:0,routes:0,hubs:0,finance:0,fuel:0,maintenance:0,company:0};for(const r of state.records){if(counts[r.category]!=null)counts[r.category]++;let o;try{o=JSON.parse(r.body)}catch{continue}walk(o,n=>{if(Array.isArray(n))return;for(const [k,v] of Object.entries(n)){const n= num(v), key=k.toLowerCase();if(n!=null&&/(cash|balance|money|funds|credits|account)/.test(key)&&n>1000)cash=Math.max(cash||0,n);if(n!=null&&/(aircraft.?count|fleet.?count|plane.?count)/.test(key))aircraft=Math.max(aircraft||0,n);if(n!=null&&/(route.?count)/.test(key))routes=Math.max(routes||0,n);if(n!=null&&/(hub.?count)/.test(key))hubs=Math.max(hubs||0,n)}})}const text=state.visibleState||'';const mm=[...text.matchAll(/(?:\$|cash|balance|account)[^\d]{0,30}([\d,]{4,})/gi)].map(m=>num(m[1])).filter(Boolean);if(mm.length)cash=Math.max(cash||0,...mm);return{cash,aircraft,routes,hubs,counts}}
function setConnected(){
  state.normalized=normalizeSnapshot({records:state.records,visibleState:state.visibleState});
  state.recommendation=recommend(state.normalized);
  const x=extract();const has=state.records.length>0||!!state.visibleState;$('#empty').classList.toggle('hidden',has);$('#dashboard-content').classList.toggle('hidden',!has);$('#sync').textContent=has?'AM4 connected':'No airline connected';$('#sync').className='pill '+(has?'':'muted');renderDashboard(x);renderTables();renderData()}
function renderDashboard(x){$('#metrics').innerHTML=[['Cash',money(x.cash)],['Aircraft',x.aircraft??'—'],['Routes',x.routes??'—'],['Hubs',x.hubs??'—'],['Captured records',state.records.length],['Source',state.source||'snapshot']].map(([a,b])=>'<div class="metric"><b>'+b+'</b><small>'+a+'</small></div>').join('');const evidence=Object.values(x.counts).reduce((a,b)=>a+b,0);const score=Math.min(100,Math.round((evidence?evidence*7:0)+(x.cash?20:0)+(x.aircraft?15:0)+(x.routes?10:0)));$('#growth-score').textContent=score||'—';const ready=state.records.length>0;$('#next-title').textContent=ready?(state.recommendation?.status==='ready'?'Review the top investment candidate':'Waiting for sufficient economics evidence'):'Connect an AM4 snapshot';
$('#next-reason').textContent=ready?(state.recommendation?.reason||'No recommendation available.'):'Connect to AM4 using the local read-only connector.';const q=[['Data normalization','Convert captured AM4 payloads into aircraft, route, hub and finance entities.','Foundation'],['Fleet economics','Calculate incremental profit, operating cost and payback for candidate aircraft.','Next'],['Route ranking','Rank routes using demand, distance, taxes and aircraft fit.','Next'],['Growth planner','Select the highest-value expansion while preserving a cash reserve.','Next']];$('#queue').innerHTML=q.map((z,i)=>'<div class="queue-item"><span class="rank">#'+(i+1)+'</span><div><b>'+z[0]+'</b><br><small>'+z[1]+'</small></div><span class="pill muted">'+z[2]+'</span></div>').join('');const missing=[];if(!x.cash)missing.push('cash');if(!x.aircraft)missing.push('fleet');if(!x.routes)missing.push('routes');if(!x.hubs)missing.push('hubs');$('#health-label').textContent=missing.length?'Partial':'Good';$('#health-label').className='pill '+(missing.length?'muted':'');$('#health').innerHTML=(missing.length?['Available evidence: '+Object.entries(x.counts).filter(([,v])=>v).map(([k,v])=>k+' ('+v+')').join(', ')||'none','Missing/undetected: '+missing.join(', ')||'none','This is a capture-quality report, not a guess.']:['Core airline fields detected.','The optimizer can proceed when payload normalization is complete.']).map(t=>'<div class="health-row">'+t+'</div>').join('')}
function renderTables(){const objs=flattenObjects(state.records);const aircraft=objs.filter(o=>o.__category==='fleet').slice(0,100);const routes=objs.filter(o=>o.__category==='routes').slice(0,100);$('#aircraft-table').innerHTML=aircraft.length?table(aircraft,['name','model','capacity','speed','range','price']):'<div class="notice">No normalized aircraft records yet. The extension has captured raw payloads, but this MVP will not pretend arbitrary JSON fields are aircraft facts.</div>';$('#route-table').innerHTML=routes.length?table(routes,['origin','destination','distance','demand','revenue','profit']):'<div class="notice">No normalized route records yet. Route optimization will appear here after the AM4 payload mapper is added.</div>';$('#circuit-content').innerHTML='<div class="big-number">Waiting for route + aircraft entities</div><div class="notice">The circuit engine will search 24h/48h/72h schedules from the normalized route graph. It will not create or modify circuits in AM4.</div>';$('#price-content').innerHTML='<div class="notice">Fuel and CO₂ values will be shown here from captured finance/resource payloads. No hard-coded current price is presented as your airline state.</div>'}
function table(rows,keys){const head=keys.map(k=>'<th>'+k+'</th>').join('');const body=rows.map(o=>'<tr>'+keys.map(k=>'<td>'+(o[k]!=null?String(o[k]):'—')+'</td>').join('')+'</tr>').join('');return'<table><thead><tr>'+head+'</tr></thead><tbody>'+body+'</tbody></table>'}
function renderData(){const cats=state.records.reduce((a,r)=>(a[r.category]=(a[r.category]||0)+1,a),{});$('#data-content').innerHTML='<div class="health-row"><b>Records</b><span>'+state.records.length+'</span></div><div class="health-row"><b>Visible state</b><span>'+(state.visibleState?state.visibleState.length+' chars':'none')+'</span></div><div class="health-row"><b>Categories</b><span>'+Object.entries(cats).map(([k,v])=>k+': '+v).join(' · ')+'</span></div><div class="notice" style="margin-top:14px">Raw captured data stays local in this app. The dashboard uses the local authenticated AM4 session. No browser extension is required and credentials are not stored in the dashboard.</div>'}
async function connect(){
  const email=window.prompt("AM4 email / username (used only by the local connector):");
  if(!email)return;
  const password=window.prompt("AM4 password (not stored):");
  if(!password)return;
  $('#sync').textContent='Connecting…';
  try{
    const r=await fetch('/api/login',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({email,password})});
    const d=await r.json();
    if(!r.ok)throw new Error(d.error||'Login failed');
    state.source='live AM4 session'; state.records=d.state?.records||[]; state.visibleState=d.state?.text||''; state.snapshot=d.state; setConnected();
  }catch(e){$('#sync').textContent='Connection failed';alert(e.message)}
}
async function refresh(){
  try{const r=await fetch('/api/state');const d=await r.json();if(!r.ok)throw new Error(d.error||'Not connected');state.source='live AM4 session';state.records=d.state?.records||[];state.visibleState=d.state?.text||'';setConnected()}
  catch{$('#sync').textContent='Not connected'}
}
async function logout(){await fetch('/api/logout',{method:'POST'}).catch(()=>{});state.records=[];state.visibleState='';state.source=null;setConnected()}
document.querySelectorAll('.nav').forEach(b=>b.onclick=()=>{document.querySelectorAll('.nav').forEach(x=>x.classList.remove('active'));document.querySelectorAll('.view').forEach(x=>x.classList.remove('active'));b.classList.add('active');$('#'+b.dataset.view).classList.add('active');$('#title').textContent=b.querySelector('span').textContent});
$('#connect').onclick=connect;
$('#connect2').onclick=connect;
$('#refresh').onclick=refresh;
$('#logout').onclick=logout;
load();